name: 'Terraform Plan'
on: [push, pull_request]
defaults:
      run:
        shell: bash

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:

      - name: Azure SP login
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
      
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'whereamI'
        run: |
          pwd && ls
          git update-index --chmod +x ./auth.sh

      - name: Set ENV variables
        uses: azure/CLI@v1
        with:
          inlineScript: |
            export ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}
            export ARM_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}
            export ARM_SUBSCRIPTION_ID=$(az account show --query id | xargs)
            export ARM_TENANT_ID=$(az account show --query tenantId | xargs)

      - name: Set ENV variables
        env:
          inlineScript: |
            ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}
            ARM_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}
            ARM_SUBSCRIPTION_ID=69fa2b01-430e-405c-a55d-1b6dcb7ae43b
            ARM_TENANT_ID==${{ secrets.AZURE_TENANT_ID }}

      - name: 'Verify'
        run: |
          echo $ARM_SUBSCRIPTION_ID
          echo $ARM_TENANT_ID
          echo "hey"

      - name: 'Terraform Setup'
        uses: hashicorp/setup-terraform@v1

      - name: 'Terraform Init'
        run: terraform init

      - name: 'Terraform Format'
        run: terraform fmt -check

      - name: 'Terraform Plan'
        run: terraform plan

      - run: echo ${{ steps.plan.outputs.stdout }}
      - run: echo ${{ steps.plan.outputs.stderr }}
      - run: echo ${{ steps.plan.outputs.exitcode }}

      - name: Azure logout
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az logout